export default function TermsOfService() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <article className="prose prose-neutral dark:prose-invert">
        <h1>Terms of Service – GUXI</h1>

        <p className="text-sm text-muted-foreground">
          Last updated: 27/12/2025
        </p>

        <p>
          Welcome to <strong>GUXI</strong> (“we”, “our”, “us”). By accessing or
          using GUXI, you agree to be bound by these Terms of Service (“Terms”).
          If you do not agree, do not use the service.
        </p>

        <h2>1. Description of Service</h2>
        <p>
          GUXI is a web application that helps users automatically generate and
          post social media content (including tweets) related to GitHub
          repository activity using AI and third-party integrations.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 13 years old to use GUXI. By using the service,
          you confirm that you meet this requirement.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You are responsible for maintaining the security of your account and
          any activity that occurs under it. You agree not to misuse the service
          or attempt unauthorized access.
        </p>

        <h2>4. Third-Party Integrations</h2>
        <p>
          GUXI integrates with third-party services such as GitHub and X
          (Twitter). Your use of those services is governed by their respective
          terms and policies. We are not responsible for their availability or
          behavior.
        </p>

        <h2>5. AI-Generated Content</h2>
        <p>
          Content generated by AI is provided “as is”. You are solely
          responsible for reviewing, approving, and publishing any generated
          content. GUXI does not guarantee accuracy, originality, or compliance
          with platform rules.
        </p>

        <h2>6. Prohibited Use</h2>
        <ul>
          <li>Use GUXI for illegal or harmful activities</li>
          <li>Post spam, abusive, or misleading content</li>
          <li>Attempt to reverse engineer or disrupt the service</li>
        </ul>

        <h2>7. Termination</h2>
        <p>
          We may suspend or terminate access to GUXI at any time for violations
          of these Terms or misuse of the service.
        </p>

        <h2>8. Disclaimer</h2>
        <p>
          GUXI is provided on an “as available” basis without warranties of any
          kind. We do not guarantee uninterrupted or error-free operation.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, GUXI shall not be liable for
          any indirect, incidental, or consequential damages arising from use of
          the service.
        </p>

        <h2>10. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of GUXI
          after changes means you accept the updated Terms.
        </p>

        <h2>11. Contact</h2>
        <p>
          If you have questions about these Terms, contact us at:
          <br />
          <a href="mailto:hi@rahul.eu.org">hi@rahul.eu.org</a>
        </p>
      </article>
    </main>
  );
}
